// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Card interface {
	IsCard()
}

type AttackDice struct {
	Red   *int `json:"red"`
	Black *int `json:"black"`
	White *int `json:"white"`
}

type Command struct {
	ID           string   `json:"id"`
	CardType     string   `json:"cardType"`
	CardSubType  string   `json:"cardSubType"`
	Name         string   `json:"name"`
	Requirements []string `json:"requirements"`
	Icon         string   `json:"icon"`
	Image        string   `json:"image"`
	Commander    *string  `json:"commander"`
	Faction      *string  `json:"faction"`
	Keywords     []string `json:"keywords"`
	Pips         int      `json:"pips"`
}

func (Command) IsCard() {}

type Keyword struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Surge struct {
	Attack  *string `json:"attack"`
	Defense *string `json:"defense"`
}

type Unit struct {
	ID           string     `json:"id"`
	Name         string     `json:"name"`
	CardType     string     `json:"cardType"`
	CardSubType  string     `json:"cardSubType"`
	Icon         string     `json:"icon"`
	Image        string     `json:"image"`
	Requirements []string   `json:"requirements"`
	Unique       *bool      `json:"unique"`
	Cost         int        `json:"cost"`
	Rank         string     `json:"rank"`
	Faction      string     `json:"faction"`
	Slots        []string   `json:"slots"`
	Keywords     []string   `json:"keywords"`
	CommandCards []*Command `json:"commandCards"`
}

func (Unit) IsCard() {}

type Upgrade struct {
	ID           string   `json:"id"`
	CardType     string   `json:"cardType"`
	CardSubType  string   `json:"cardSubType"`
	Name         string   `json:"name"`
	Requirements []string `json:"requirements"`
	Icon         string   `json:"icon"`
	Image        string   `json:"image"`
	Unique       *bool    `json:"unique"`
	Cost         int      `json:"cost"`
	Keywords     []string `json:"keywords"`
}

func (Upgrade) IsCard() {}

type Weapon struct {
	Name     *string      `json:"name"`
	Range    *WeaponRange `json:"range"`
	Dice     *AttackDice  `json:"dice"`
	Keywords []string     `json:"keywords"`
}

type WeaponRange struct {
	From int  `json:"from"`
	To   *int `json:"to"`
}
